spring:
  profiles:
    active: dev
  application:
    name: movify
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: MOVIFY
  swagger-ui:
    path: /swagger-ui.html
    packagesToScan:
      com.ricardocreates.infra.rest
  cache:
    jcache:
      config: classpath:ehcache.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss