spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:appDbTest;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS movify
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: false
  liquibase:
    contexts: faker,test
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          nodeValue: TRACE
        SQL: DEBUG
    com:
      ricardocreates: TRACE
    root: WARN